name: "c3"
stack:
  - "{{ cookiecutter.region }}/network/vpc"
  - "{{ cookiecutter.region }}/citizen/keys"
  - "{{ cookiecutter.region }}/citizen/iam"
  - "{{ cookiecutter.region }}/citizen/sg"
  - "{{ cookiecutter.region }}/citizen/packer"
  - "{{ cookiecutter.region }}/citizen/user-data"
  - "{{ cookiecutter.region }}/citizen/ec2"
  - "{{ cookiecutter.region }}/citizen/ec2-configuration"
#  - "{{ cookiecutter.region }}/preptools/registration"
